# version: '3.8'

# services:
#   frontend:
#     build:
#       context: .
#       dockerfile: Dockerfile
#       args:
#         VITE_API_BASE_URL: ${VITE_API_BASE_URL}
#     container_name: frontend-jd
#     ports:
#       - "${FRONTEND_PORT}:80"
#     networks:
#       - backend-network

# networks:
#   backend-network:
#     name: jd-analyzer-network
#     external: true


version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-jd
    
    networks:
      - backend-network

networks:
  backend-network:
    name: jd-analyzer-network
    external: true

