# Frontend CI/CD Workflow for React/Vite

name: Frontend CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js 20
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install npm dependencies
      - name: Install dependencies
        run: npm ci

      # Run tests with coverage using Vitest
      - name: Run tests
        run: npm run test:coverage

      # Build the production-ready frontend
      - name: Build
        run: npm run build

      # Upload the build output as an artifact
      - name: Upload production-ready build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: dist

      # Build the Docker image for the frontend
      - name: Build Docker image
        run: |
          docker build -t frontend-jd-analyzer:latest .

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      # Download the build artifact from the previous job
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: dist

      # Example: Deploy to GitHub Pages (or replace with your own deployment step)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      # For custom server deployment, replace above with your deployment script or action


