# Continuous Integration Workflow
# Handles code quality, testing, and building for React/Vite frontend

name: CI - Build and Test

on:
  push:
    branches: 
      - main
      - formatImpjd
      - clrcode
  pull_request:
    branches: 
      - main

env:
  NODE_VERSION: 20
  CACHE_DEPENDENCY_PATH: package-lock.json

jobs:
  ci:
    name: Build, Test & Quality Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.CACHE_DEPENDENCY_PATH }}

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Run tests with coverage
        run: |
          npm run test:coverage
          echo ""
          echo "📊 Coverage Summary:"
          echo "==================="
        env:
          CI: true

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        if: success()
        with:
          file: ./coverage/lcov.info
          fail_ci_if_error: false
          verbose: true

      - name: Build production bundle
        run: npm run build
        env:
          NODE_ENV: production

      - name: Analyze bundle size
        run: |
          echo "Build completed successfully!"
          echo "Build output size:"
          du -sh dist/
          ls -la dist/

      - name: ⬆ Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build-${{ github.sha }}
          path: dist/
          retention-days: 7
          compression-level: 6

      - name: Upload source for Docker
        uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/main'
        with:
          name: source-code-${{ github.sha }}
          path: |
            .
            !node_modules
            !.git
            !dist
          retention-days: 1
